security:
    role_hierarchy:
        ROLE_SFS_CMS_ADMIN_CONTENTS_EXPORT:
            - PERMISSION_SFS_CMS_ADMIN_CONTENT_VERSION_EXPORT
        ROLE_SFS_CMS_ADMIN_CONTENTS_IMPORT:
            - PERMISSION_SFS_CMS_ADMIN_CONTENT_IMPORT
            - PERMISSION_SFS_CMS_ADMIN_CONTENT_VERSION_IMPORT

